title:            Johnny Sunshine
description:      Long form words
url:              # Site url.
signoff:          John Sonnenschein
links:
  - name:         Blog
    url:          /
  - name:         Email
    url:          mailto:johnsonnenschein@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/sonnens
    external:     true
  - name:         Twitter
    url:          https://twitter.com/johnnysunshine
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
